---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: slacker-dumper
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/vaikas-google/twitter/cmd/slacker
            env:
            - name: SLACKER_TARGET
              valueFrom:
                secretKeyRef:
                  key: slack-post-url
                  name: slack-secret

